backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
- label: "RaceInfo"
  name: "raceinfo"
  folder: "content/raceinfo"
  filter: {field: "type", value: "raceinfo"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image}
    - {label: Order, name: order, widget: number, required: false}
    - {label: Content, name: body, widget: markdown}
- label: "RaceWeekend"
  name: "raceweekend"
  folder: "content/raceweekend"
  filter: {field: "type", value: "raceweekend"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image}
    - {label: Order, name: order, widget: number, required: false}
    - {label: Content, name: body, widget: markdown}
- label: "FAQ"
  name: "faq"
  folder: "content/faq"
  filter: {field: "type", value: "raceinfo"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image}
    - {label: Order, name: order, widget: number, required: false}
    - {label: Content, name: body, widget: markdown}
- label: "Pages"
  name: "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - label: Slides
          name: slides
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
            - {label: Title, name: title, widget: string}
            - {label: Description, name: description, widget: text}
            - {label: Link, name: link, widget: string}
        - {label: Content, name: body, widget: markdown}
    - label: "Contact Page"
      name: "contact"
      file: "content/contact/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Google Map Coordinates, name: google_map_coordinates, widget: string}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Business Name, name: business_name, widget: string}
        - {label: Address, name: address, widget: text}
        - {label: Telephone No, name: phone, widget: string}
        - {label: Phone No, name: mobile, widget: string}
        - {label: Email, name: email, widget: string}
        - {label: Content, name: body, widget: markdown}
- label: "Data"
  name: "data"
  files:
    - label: "Marathon Type"
      name: "marathon_type"
      file: "data/marathon_type.yml"
      fields:
        - label: Marathon Type
          name: marathon_type
          widget: list
          fields:
            - {label: Name, name: name, widget: string}
            - {label: Distance, name: distance, widget: string}
            - {label: "Date", name: "date", widget: "date"}
            - {label: Link, name: link, widget: string}
    
    - label: "Meta"
      name: "meta"
      file: "data/meta.yml"
      fields:
        - {label: Page Background, name: background_image, widget: image}
        - {label: Logo, name: logo, widget: image}
        - {label: FB Cover, name: fb_cover, widget: image}
